// <auto-generated />
namespace BalloonShop.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSPDept : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSPDept));
        
        string IMigrationMetadata.Id
        {
            get { return "201703151030037_AddSPDept"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
